name: DockerBuild
on:
  push:
    branches:
      - "master"
    paths:
      - "cogs/**"
      - "data/**"
      - "enka_network/**"
      - "genshin_db/**"
      - "genshin_py/**"
      - "utility/**"
      - ".dockerignore"
      - "Dockerfile"
      - "main.py"
      - "Pipfile.lock"
      - "start.sh"
  workflow_dispatch: {}
jobs:
  DockerBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checking Repostiory
        uses: actions/checkout@v3
      - name: Setup multiarch
        uses: docker/setup-qemu-action@v2
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/kt-yeh/genshin-discord-bot:latest
